In [62]:
import numpy as np
import pandas as pd
import regex as re
import os

In [63]:
effect_df = pd.read_csv('Achilles_gene_effect.csv')
label_df = pd.read_csv('/Users/jiamingxu/Downloads/sample_info.csv')
#mutation_df = pd.read_csv('CCLE_mutations.csv')

In [65]:
ID_to_Organ = {}
for i in range(label_df.shape[0]):
    ID_to_Organ[label_df.loc[i, 'DepMap_ID']] = label_df.loc[i, 'lineage']

In [66]:
for i in range(effect_df.shape[0]):
    effect_df.loc[i, 'lineage'] = ID_to_Organ[effect_df.loc[i, 'DepMap_ID']]

In [67]:
effect_df.columns = ['DepID']+list((np.array(re.findall('(\S+)\ (\S+) ', " "+" ".join(effect_df.columns))).reshape(1, -1))[0][1::2]) +['lineage']
cancer_types = ['kidney', 'liver', 'pancreas', 'urinary_tract', 'ovary', 'colorectal', 'breast', 'lung', 'lymphocyte']

In [68]:
for ct in cancer_types:
    effect_df.loc[effect_df['lineage'].str.contains(ct)].drop(columns=['DepID', 'lineage']).reset_index(drop = True, inplace=False).transpose().to_csv('{}_CRISPR_gene_effect.csv'.format(ct))

In [27]:
re.findalleffect_df.columns

Index(['DepMap_ID', 'A1BG (1)', 'A1CF (29974)', 'A2M (2)', 'A2ML1 (144568)',
       'A3GALT2 (127550)', 'A4GALT (53947)', 'A4GNT (51146)', 'AAAS (8086)',
       'AACS (65985)',
       ...
       'ZWINT (11130)', 'ZXDA (7789)', 'ZXDB (158586)', 'ZXDC (79364)',
       'ZYG11A (440590)', 'ZYG11B (79699)', 'ZYX (7791)', 'ZZEF1 (23140)',
       'ZZZ3 (26009)', 'lineage'],
      dtype='object', length=18019)

In [52]:
effect_df.columns = ['DepID']+list((np.array(re.findall('(\S+)\ (\S+) ', " "+" ".join(effect_df.columns))).reshape(1, -1))[0][1::2]) +['lineage']

In [61]:
effect_df.loc[effect_df['lineage'].str.contains(ct)].drop(columns=['DepID', 'lineage']).reset_index(drop = True, inplace=False).transpose()

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
A1BG,0.060527,-0.042369,-0.019901,0.081881,0.032301,0.107169,-0.083175,0.062912,0.065051,-0.024459,...,0.168317,0.047972,0.022378,0.191699,0.017281,0.114262,-0.001762,-0.076144,-0.054653,-0.091412
A1CF,0.028777,-0.060624,0.063839,0.062624,0.104029,0.039917,0.033579,0.090902,-0.051350,0.081581,...,0.193313,0.043214,0.011580,-0.033011,-0.084736,0.046414,0.148771,0.202793,-0.139748,0.082384
A2M,-0.055936,-0.292337,-0.098839,0.016777,-0.117086,-0.061128,-0.087905,-0.194066,-0.097480,-0.201342,...,-0.232136,-0.062004,0.282508,-0.316777,0.011164,-0.378795,-0.061599,-0.004699,0.051743,-0.089843
A2ML1,0.030910,-0.083724,-0.011501,0.040359,0.000751,-0.063520,0.003603,-0.117806,-0.005757,0.105713,...,0.054834,0.098920,0.100669,0.066634,-0.002316,0.096081,0.035316,0.023201,-0.220647,0.132463
A3GALT2,0.058460,0.229044,-0.151501,0.028385,0.102353,0.050172,0.066367,0.121344,0.108115,0.049055,...,-0.045460,-0.074959,-0.004335,-0.037478,0.031046,0.073240,0.214282,0.027886,0.060914,0.095774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,-0.020958,0.197830,0.019185,0.088487,0.060167,-0.053805,-0.088563,0.161520,-0.029411,0.120991,...,0.000839,0.101834,-0.018502,-0.014039,0.037045,0.183477,0.196375,0.080991,0.110525,-0.096362
ZYG11B,-0.037895,-0.111725,-0.204176,-0.008162,0.062744,0.125971,-0.128149,0.109379,0.102714,-0.087038,...,-0.101406,-0.167173,-0.108768,-0.212509,0.134434,-0.357260,-0.079279,0.072181,0.131412,-0.242658
ZYX,-0.037342,0.036673,0.171171,0.065422,0.105162,0.146169,0.147596,0.087106,0.126524,0.153338,...,0.099113,0.111968,0.050964,0.303153,0.003918,-0.040440,-0.007735,0.028235,-0.155230,0.162692
ZZEF1,-0.062693,-0.199478,-0.259088,-0.099669,-0.237658,-0.138721,-0.114305,-0.092938,0.099976,-0.489742,...,-0.100489,-0.180864,-0.080981,-0.189988,-0.008977,-0.202130,-0.425713,-0.001972,0.118777,-0.368395
ZZZ3,-0.086448,-0.148502,-0.110914,-0.116748,-0.183339,-0.198327,-0.131299,-0.145900,-0.317194,-0.065698,...,-0.020345,-0.163777,-0.412080,-0.564579,-0.356231,-0.196079,-0.129827,-0.032026,-0.047610,-0.040978

KeyError: "None of [Index(['blood', 'blood', 'colorectal', 'colorectal', 'urinary_tract', 'lung',\n       'ovary', 'skin', 'lung', 'breast',\n       ...\n       'eye', 'peripheral_nervous_system', 'peripheral_nervous_system',\n       'soft_tissue', 'peripheral_nervous_system', 'bone', 'unknown', 'skin',\n       'skin', 'unknown'],\n      dtype='object', length=957)] are in the [index]"

In [179]:
## Loading centre nerverous systems
df = pd.read_csv('/Users/jiamingxu/Downloads/Dataset/CRISPR_gene_effect_central_nervous_system.csv')

In [180]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [181]:
gene_names = re.findall(' (\S+) ', " ".join(df.columns))

In [182]:
gene_targets = [ 'positive' if x < 0 else 'negative' for x in np.median(df.iloc[:, 2:-1], axis=0)]
gene_median = np.median(df.iloc[:, 2:-1], axis=0)

In [183]:
a = pd.DataFrame(columns=df.columns[2:-1])
a.loc[1] = gene_median
a.loc[2] = gene_targets

In [192]:
effect_df = a.transpose()
effect_df.columns = ['Median', 'Target']
effect_df['Symbol'] = re.findall(' (\S+) ', " "+" ".join(effect_df.index))
effect_df['Id'] = re.findall('\((\S+)\)', " "+" ".join(effect_df.index))

In [195]:
positive_genes  = np.array(effect_df.sort_values('Median').iloc[:num_positive_genes]['Symbol'])
negative_genes = np.array(effect_df.sort_values('Median').iloc[-num_negative_genes:]['Symbol'])

In [196]:
expression_df = pd.read_csv('/Users/jiamingxu/Downloads/CCLE_expression.csv')

In [197]:
expression_df.head()

,Unnamed: 0,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),C1orf112 (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),...,H3C2 (8358),H3C3 (8352),AC098582.1 (8916),DUS4L-BCAP29 (115253422),C8orf44-SGK3 (100533105),ELOA3B (728929),NPBWR1 (2831),ELOA3D (100506888),ELOA3 (162699),CDR1 (1038)
0,ACH-001113,4.331992,0.000000,7.364397,2.792855,4.470537,0.028569,1.226509,3.042644,6.499686,...,2.689299,0.189034,0.201634,2.130931,0.555816,0.0,0.275007,0.0,0.0,0.000000
1,ACH-001289,4.566815,0.584963,7.106537,2.543496,3.504620,0.000000,0.189034,3.813525,4.221104,...,1.286881,1.049631,0.321928,1.464668,0.632268,0.0,0.014355,0.0,0.0,0.000000
2,ACH-001339,3.150560,0.000000,7.379032,2.333424,4.227279,0.056584,1.310340,6.687061,3.682573,...,0.594549,1.097611,0.831877,2.946731,0.475085,0.0,0.084064,0.0,0.0,0.042644
3,ACH-001538,5.085340,0.000000,7.154109,2.545968,3.084064,0.000000,5.868143,6.165309,4.489928,...,0.214125,0.632268,0.298658,1.641546,0.443607,0.0,0.028569,0.0,0.0,0.000000
4,ACH-000242,6.729145,0.000000,6.537607,2.456806,3.867896,0.799087,7.208381,5.569856,7.127014,...,1.117695,2.358959,0.084064,1.910733,0.000000,0.0,0.464668,0.0,0.0,0.000000

In [198]:
positive_genes

array(['DUX4', 'RAN', 'RPL12', 'HSPE1', 'RPL37', 'RPL9', 'PRPF38B',
       'RPS3A', 'TXNL4A', 'SNRPB', 'FAU', 'RPL17', 'RPSA', 'RPL4',
       'POLR2L', 'EEF1A1', 'RPL15', 'RPS13', 'RPL8', 'CDC45', 'PSMD7',
       'CNIH4', 'PRELID1', 'MED30', 'ATP6V0C', 'RPS20', 'KRT8', 'HSPA5',
       'RRM1', 'RRM2', 'SNRNP200', 'BUB3', 'EIF6', 'RPS29', 'SS18L2',
       'RPLP0', 'DONSON', 'RPS8', 'RPL23', 'RPL11', 'EEF2', 'CDC5L',
       'RPS19', 'GPN3', 'RRN3', 'RPL41', 'PCNA', 'RPS6', 'TRMT112',
       'EEF2KMT', 'PSMA1', 'CDK7', 'PSMB3', 'RPS28', 'SRSF7', 'RPL7A',
       'RPL23A', 'NUS1', 'RPS27', 'RNPC3', 'FARSB', 'PAFAH1B1', 'SARS1',
       'PSMA3', 'SNRPD1', 'RAD21', 'HNRNPK', 'CDC123', 'USP5', 'ANKLE2',
       'RPS10', 'DAD1', 'SNRPA1', 'RPLP2', 'RPL6', 'LSM2', 'GINS2',
       'DPAGT1', 'WDR43', 'PRPF38A', 'RPS2', 'WEE1', 'SPC24', 'CDC27',
       'PPIA', 'ESPL1', 'SNRPG', 'KPNB1', 'ANAPC4', 'KIF11', 'TIGD1',
       'ANAPC2', 'ETF1', 'RPS27A', 'POLR3K', 'RPL31', 'RPL10A', 'NEDD1',
       'UBL5', 'RPS4X'], dtype=object)

In [82]:
'AGPAT1' in all_genes_

True

In [81]:
all_ge

Index(['100130426', '100133144', '100134869', '10357', '10431', '136542',
       '155060', '26823', '280660', '317712',
       ...
       'ZWILCH', 'ZWINT', 'ZXDA', 'ZXDB', 'ZXDC', 'ZYG11A', 'ZYG11B', 'ZYX',
       'ZZEF1', 'ZZZ3'],
      dtype='object', name='sample', length=20531)

In [96]:
mutation_df.dropna(axis=1)

,Hugo_Symbol,Entrez_Gene_Id,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Alternate_Allele,Genome_Change,DepMap_ID,isTCGAhotspot,Variant_annotation
0,VPS13D,55187,37,1,12359347,12359347,+,Nonsense_Mutation,SNP,C,A,g.chr1:12359347C>A,ACH-000001,False,damaging
1,AADACL4,343066,37,1,12726308,12726322,+,In_Frame_Del,DEL,CTGGCGTGACGCCAT,-,g.chr1:12726308_12726322delCTGGCGTGACGCCAT,ACH-000001,False,other non-conserving
2,IFNLR1,163702,37,1,24484172,24484172,+,Silent,SNP,G,A,g.chr1:24484172G>A,ACH-000001,False,silent
3,TMEM57,55219,37,1,25785018,25785019,+,Frame_Shift_Ins,INS,-,A,g.chr1:25785018_25785019insA,ACH-000001,False,damaging
4,ZSCAN20,7579,37,1,33954141,33954141,+,Missense_Mutation,SNP,T,G,g.chr1:33954141T>G,ACH-000001,False,other non-conserving
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1235461,GSN,2934,37,9,124064366,124064366,+,Silent,SNP,C,T,g.chr9:124064366C>T,ACH-002926,False,silent
1235462,NOTCH1,4851,37,9,139390940,139390940,+,Silent,SNP,C,T,g.chr9:139390940C>T,ACH-002926,False,silent
1235463,MAGEC1,9947,37,X,140995050,140995050,+,Missense_Mutation,SNP,A,C,g.chrX:140995050A>C,ACH-002926,False,other non-conserving
1235464,MAGEA3,4102,37,X,151935812,151935812,+,Missense_Mutation,SNP,A,C,g.chrX:151935812A>C,ACH-002926,False,other non-conserving
1235465,VAMP7,6845,37,X,155127785,155127785,+,Missense_Mutation,SNP,C,T,g.chrX:155127785C>T,ACH-002926,False,other non-conserving

In [50]:
interactions_df = pd.read_csv('https://www.dgidb.org/data/monthly_tsvs/2022-Feb/interactions.tsv', sep='\t')

In [56]:
interactions_df['interaction_types'].drop_na()

AttributeError: 'Series' object has no attribute 'drop_na'

In [52]:
interactions_df = pd.read_csv('https://www.dgidb.org/data/monthly_tsvs/2021-May/interactions.tsv', sep='\t')

In [60]:
interactions_df.head()

,gene_name,gene_claim_name,entrez_id,interaction_claim_source,interaction_types,drug_claim_name,drug_claim_primary_name,drug_name,drug_concept_id,interaction_group_score,PMIDs
0,CDK7,CDK7,1022.0,CancerCommons,inhibitor,SNS-032,SNS-032,BMS-387032,chembl:CHEMBL296468,0.82,NaN
1,VDR,VDR,7421.0,DTC,NaN,NIFEKALANT,NIFEKALANT,NIFEKALANT,chembl:CHEMBL360861,0.12,NaN
2,GPR55,GPR55,9290.0,DTC,NaN,BISACODYL,BISACODYL,BISACODYL,chembl:CHEMBL942,0.75,NaN
3,DPYD,BE0000960,1806.0,DrugBank,NaN,DB03419,Uracil,URACIL,chembl:CHEMBL566,2.52,"10592235,17139284,17016423"
4,NR1H4,NR1H4,9971.0,DTC,NaN,PENTACHLOROPHENOL,PENTACHLOROPHENOL,PENTACHLOROPHENOL,chembl:CHEMBL75967,0.06,NaN

In [70]:
interactions_df.dropna(subset = ['interaction_types', 'drug_name'], inplace=True)

In [76]:
len(list(set(interactions_df['gene_name'])))

2262

In [79]:
import regex as re

In [175]:
gene_names = re.findall(' (\S+) ', " ".join(effect_df.columns))
gene_ids = re.findall('\(\S+\) ', " ".join(effect_df.columns))

In [176]:
gene_ids

[]

In [129]:
interactions_df

,gene_name,gene_claim_name,entrez_id,interaction_claim_source,interaction_types,drug_claim_name,drug_claim_primary_name,drug_name,drug_concept_id,interaction_group_score,PMIDs
0,CDK7,CDK7,1022.0,CancerCommons,inhibitor,SNS-032,SNS-032,BMS-387032,chembl:CHEMBL296468,0.82,NaN
12,PDGFRB,PDGFR,5159.0,ChemblInteractions,inhibitor,CHEMBL576982,QUIZARTINIB,QUIZARTINIB,chembl:CHEMBL576982,0.15,NaN
14,OPRK1,BE0000632,4986.0,DrugBank,agonist,DB00327,Hydromorphone,HYDROMORPHONE,chembl:CHEMBL398707,0.71,"16433932,17139284,17016423"
19,PIK3R2,PIK3R2,5296.0,MyCancerGenome,inhibitor,PF-4691502,PF-4691502,PF-04691502,chembl:CHEMBL1234354,0.18,NaN
31,F2R,CF2R,2149.0,ChemblInteractions,inhibitor,CHEMBL2013119,RIGOSERTIB SODIUM,RIGOSERTIB SODIUM,chembl:CHEMBL2013119,3.34,NaN
...,...,...,...,...,...,...,...,...,...,...,...
100256,ACE,1636,1636.0,GuideToPharmacology,inhibitor,178102940,ENALAPRIL,ENALAPRIL,chembl:CHEMBL578,0.60,NaN
100257,SCN11A,SCN12A,11280.0,ChemblInteractions,blocker,CHEMBL2107771,RALFINAMIDE,RALFINAMIDE,chembl:CHEMBL2107771,0.05,NaN
100263,ADRB2,BE0000694,154.0,DrugBank,agonist,DB01001,Salbutamol,ALBUTEROL,chembl:CHEMBL714,0.95,"14757145,12808710,15557128,11752352,12569076,1..."
100264,ADRA1A,BE0000501,148.0,DrugBank,antagonist,DB01267,Paliperidone,PALIPERIDONE,chembl:CHEMBL1621,0.14,"15992090,18542932,8925876,11132243,7524043,769..."
100268,PIK3C3,PIK3C3,5289.0,MyCancerGenome,inhibitor,BGJ398,BGJ398,INFIGRATINIB,chembl:CHEMBL1852688,0.15,NaN

In [132]:
pd.read_csv('https://www.dgidb.org/data/monthly_tsvs/2022-Feb/categories.tsv', sep='\t')

,entrez_gene_symbol,gene_long_name,category_sources,category
0,IDI2,ISOPENTENYL-DIPHOSPHATE DELTA ISOMERASE 2,GuideToPharmacology,ENZYME
1,WDR11,WD REPEAT DOMAIN 11,Pharos,TRANSCRIPTION FACTOR
2,KIF20B,KINESIN FAMILY MEMBER 20B,GO,TUMOR SUPPRESSOR
3,KIF20B,KINESIN FAMILY MEMBER 20B,Pharos,ENZYME
4,SDF2,STROMAL CELL DERIVED FACTOR 2,HingoraniCasas,DRUGGABLE GENOME
...,...,...,...,...
19965,SEMA3C,SEMAPHORIN 3C,HingoraniCasas,DRUGGABLE GENOME
19966,PSMA8,PROTEASOME SUBUNIT ALPHA 8,HingoraniCasas,DRUGGABLE GENOME
19967,PSMA8,PROTEASOME SUBUNIT ALPHA 8,dGene,PROTEASE
19968,OR52I2,OLFACTORY RECEPTOR FAMILY 52 SUBFAMILY I MEMBER 2,"dGene,GO,Pharos,HopkinsGroom",G PROTEIN COUPLED RECEPTOR
19969,OR52I2,OLFACTORY RECEPTOR FAMILY 52 SUBFAMILY I MEMBER 2,"RussLampel,HopkinsGroom",DRUGGABLE GENOME

In [200]:
gp_df_clean['Symbol'].shape

(17705,)

In [171]:
gp_df = pd.read_csv("/Users/jiamingxu/Library/CloudStorage/OneDrive-NortheasternUniversity/Fall 2022/STAT/github/XNProject/Dataset/protein-coding-genes.tsv"\
                    , sep='\t', names=['Description', 'Symbol', 'Protein_Name']).dropna().drop_duplicates('Symbol')
gp_df_clean = gp_df[gp_df['Symbol'].isin(gene_names)]
gp_df_clean = gp_df_clean[gp_df_clean['Protein_Name'].str.contains("HUMAN")]
#gp_df['Protein_Name'].str.contains("HUMAN")
gp_df_clean.reset_index()
protein_gene_interaction_names = gp_df_clean['Symbol']

In [199]:
gp_df_clean

,Description,Symbol,Protein_Name
0,"1,4-alpha-glucan branching enzyme 1",GBE1,GLGB_HUMAN
1,1-acylglycerol-3-phosphate O-acyltransferase 1,AGPAT1,PLCA_HUMAN
2,1-acylglycerol-3-phosphate O-acyltransferase 2,AGPAT2,A0A024R8F9_HUMAN
5,1-acylglycerol-3-phosphate O-acyltransferase 3,AGPAT3,PLCC_HUMAN
8,1-acylglycerol-3-phosphate O-acyltransferase 4,AGPAT4,PLCD_HUMAN
...,...,...,...
48873,zygote arrest 1,ZAR1,B9EG67_HUMAN
48875,zygote arrest 1 like,ZAR1L,ZAR1L_HUMAN
48876,zymogen granule protein 16,ZG16,ZG16_HUMAN
48877,zymogen granule protein 16B,ZG16B,ZG16B_HUMAN
48878,zyxin,ZYX,ZYX_HUMAN

### Features processing

In [3]:
os.chdir('/Users/jiamingxu/Downloads')

In [10]:
df = pd.read_csv('CCLE_mutations.csv')#, sep = '\t')

/var/folders/98/j3jkkz5155b37m2g25kcs2ph0000gn/T/ipykernel_66105/2457403836.py:1: DtypeWarning: Columns (3,19,22,27,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('CCLE_mutations.csv')#, sep = '\t')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1235466 entries, 0 to 1235465
Data columns (total 32 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Hugo_Symbol             1235466 non-null  object
 1   Entrez_Gene_Id          1235466 non-null  int64
 2   NCBI_Build              1235466 non-null  int64
 3   Chromosome              1235466 non-null  object
 4   Start_position          1235466 non-null  int64
 5   End_position            1235466 non-null  int64
 6   Strand                  1235466 non-null  object
 7   Variant_Classification  1235466 non-null  object
 8   Variant_Type            1235466 non-null  object
 9   Reference_Allele        1235466 non-null  object
 10  Alternate_Allele        1235466 non-null  object
 11  dbSNP_RS                195292 non-null   object
 12  dbSNP_Val_Status        36754 non-null    object
 13  Genome_Change           1235466 non-null  object
 14  Annotation_Transcript   1235379 non-null  object
 15  DepMap_ID               1235466 non-null  object
 16  cDNA_Change             1209275 non-null  object
 17  Codon_Change            1230039 non-null  object
 18  Protein_Change          1209267 non-null  object
 19  isDeleterious           1235465 non-null  object
 20  isTCGAhotspot           1235466 non-null  bool
 21  TCGAhsCnt               263274 non-null   float64
 22  isCOSMIChotspot         1235452 non-null  object
 23  COSMIChsCnt             1235400 non-null  float64
 24  ExAC_AF                 289288 non-null   float64
 25  Variant_annotation      1235466 non-null  object
 26  CGA_WES_AC              996509 non-null   object
 27  HC_AC                   85113 non-null    object
 28  RD_AC                   2127 non-null     object
 29  RNAseq_AC               381871 non-null   object
 30  SangerWES_AC            629327 non-null   object
 31  WGS_AC                  262194 non-null   object
dtypes: bool(1), float64(3), int64(4), object(24)
memory usage: 293.4+ MB

In [12]:
df.head()

,Hugo_Symbol,Entrez_Gene_Id,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,...,isCOSMIChotspot,COSMIChsCnt,ExAC_AF,Variant_annotation,CGA_WES_AC,HC_AC,RD_AC,RNAseq_AC,SangerWES_AC,WGS_AC
0,VPS13D,55187,37,1,12359347,12359347,+,Nonsense_Mutation,SNP,C,...,False,0.0,NaN,damaging,34:213,NaN,NaN,NaN,34:221,NaN
1,AADACL4,343066,37,1,12726308,12726322,+,In_Frame_Del,DEL,CTGGCGTGACGCCAT,...,False,3.0,NaN,other non-conserving,57:141,NaN,NaN,NaN,9:0,28:32
2,IFNLR1,163702,37,1,24484172,24484172,+,Silent,SNP,G,...,False,0.0,NaN,silent,118:0,NaN,NaN,10:0,118:0,18:0
3,TMEM57,55219,37,1,25785018,25785019,+,Frame_Shift_Ins,INS,-,...,False,0.0,NaN,damaging,NaN,NaN,NaN,6:28,NaN,NaN
4,ZSCAN20,7579,37,1,33954141,33954141,+,Missense_Mutation,SNP,T,...,False,0.0,NaN,other non-conserving,28:62,NaN,NaN,NaN,27:61,NaN

In [13]:
df = pd.read_csv('denseDataOnlyDownload.tsv' , sep = '\t')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12839 entries, 0 to 12838
Columns: 425 entries, sample to A1BG (average)
dtypes: float64(423), object(2)
memory usage: 41.6+ MB

In [16]:
df

,sample,samples,TOP2A,POLA1,MDM4,TUBB8,TUBB2B,TUBA1A,TBL1XR1,TUBA1C,...,MPHOSPH9,SEMA6D,MUCL1,CDH26,ITPKA,CCDC110,SPINK6,BAK1,HBA1,A1BG (average)
0,TCGA-R6-A8WC-01,TCGA-R6-A8WC-01,16.55,10.30,10.61,1.92,5.23,9.03,12.56,12.74,...,9.66,7.42,0.02,1.03,8.24,5.57,-0.02,9.68,4.78,-0.3172
1,TCGA-VR-AA4D-01,TCGA-VR-AA4D-01,16.26,9.93,10.49,2.13,7.90,9.64,12.05,12.69,...,8.35,3.73,0.02,1.00,8.21,6.13,-0.02,9.58,6.08,-0.1167
2,TCGA-BH-A0DD-01,TCGA-BH-A0DD-01,15.84,9.83,10.81,3.73,4.41,12.56,11.99,12.02,...,9.60,4.63,6.23,4.01,3.00,5.42,0.00,8.68,0.00,0.2099
3,TCGA-LN-A49L-01,TCGA-LN-A49L-01,15.81,9.84,9.99,4.84,8.10,11.42,12.54,13.76,...,9.43,6.04,6.57,3.82,5.04,5.89,-0.02,9.05,2.13,-0.2803
4,TCGA-R5-A7ZE-01,TCGA-R5-A7ZE-01,15.75,9.39,9.06,1.32,9.31,10.66,11.53,14.27,...,7.70,4.78,3.94,5.04,6.43,3.20,8.17,9.79,7.72,-0.3113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12834,TCGA-O2-A5IC-01,TCGA-O2-A5IC-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12835,TCGA-SW-A7EA-11,TCGA-SW-A7EA-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12836,TCGA-V5-A7RE-11,TCGA-V5-A7RE-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12837,TCGA-V5-AASX-11,TCGA-V5-AASX-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12838,TCGA-XV-AB01-01,TCGA-XV-AB01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Write a for loop to save mutation/expression of genes as csv file for each cancer type.

In [72]:
# Read mutation or expression
os.chdir('/Users/jiamingxu/Downloads')
df = pd.read_csv('EB++AdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.xena', sep = '\t', index_col = 0)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20531 entries, 100130426 to ZZZ3
Columns: 11069 entries, TCGA-OR-A5J1-01 to TCGA-CG-4477-01
dtypes: float64(11069)
memory usage: 1.7+ GB

In [74]:
df.head()

,TCGA-OR-A5J1-01,TCGA-OR-A5J2-01,TCGA-OR-A5J3-01,TCGA-OR-A5J5-01,TCGA-OR-A5J6-01,TCGA-OR-A5J7-01,TCGA-OR-A5J8-01,TCGA-OR-A5J9-01,TCGA-OR-A5JA-01,TCGA-OR-A5JB-01,...,TCGA-CG-4449-01,TCGA-CG-4462-01,TCGA-CG-4465-01,TCGA-CG-4466-01,TCGA-CG-4469-01,TCGA-CG-4472-01,TCGA-CG-4474-01,TCGA-CG-4475-01,TCGA-CG-4476-01,TCGA-CG-4477-01
sample,,,,,,,,,,,,,,,,,,,,,
100130426,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100133144,2.09,1.88,1.45,0.00,0.00,1.12,1.29,0.00,2.45,3.02,...,2.42,2.74,2.64,3.99,4.40,3.00,4.27,3.71,4.29,4.24
100134869,2.30,3.32,2.92,1.35,2.45,2.82,1.72,1.24,2.60,0.00,...,1.87,2.12,1.78,2.60,3.66,3.87,3.07,3.65,3.64,3.99
10357,7.23,6.36,6.45,5.78,6.09,6.71,6.58,6.31,6.13,7.29,...,9.31,8.20,9.43,9.14,10.02,9.32,9.54,8.99,9.48,9.46
10431,10.99,10.35,10.04,11.20,10.30,10.87,9.96,10.78,10.25,10.97,...,10.23,9.33,10.21,9.38,9.34,10.34,10.17,10.43,9.93,10.76

In [75]:
os.chdir('/Users/jiamingxu/Library/CloudStorage/OneDrive-NortheasternUniversity/Fall 2022/STAT/github/XNProject/Dataset/training_set')

In [76]:
training_csv_files = []
for file_ in os.scandir():
    if file_.name.endswith('csv'):
        training_csv_files.append(file_.name)

In [77]:
all_genes_ = df.index

In [79]:
for csv_file in training_csv_files:
    train_df = pd.read_csv(csv_file)
    genes_ = train_df.iloc[:,0]
    ava_genes_ = [ x for x in genes_ if x in all_genes_ ]
    df.loc[ava_genes_, :].to_csv(csv_file.split('_')[0] + '_gene_expressions.csv')